REENTRY_MODES = ("RE_ASAP", "RE_ASAP_REVERSE", "RE_COST", "RE_COST_REVERSE", "RE_MOMENTUM", "RE_MOMENTUM_REVERSE", "LAZY_LEG")

OVERALL_REENTRY_MODES = ("RE_ASAP", "RE_ASAP_REVERSE", "RE_MOMENTUM", "RE_MOMENTUM_REVERSE")

QUANTITY = 100

COST_BUFFER_PCT = 0.05