REENTRY_MODES = ("RE_ASAP", "RE_ASAP_REVERSE", "RE_COST", "RE_COST_REVERSE", "RE_MOMENTUM", "RE_MOMENTUM_REVERSE", "LAZY_LEG")

OVERALL_REENTRY_MODES = ("RE_ASAP", "RE_ASAP_REVERSE", "RE_MOMENTUM", "RE_MOMENTUM_REVERSE")

# Sensex option lot size (BSE, since Nov 2024). PnL = price move * QUANTITY * lot_size.
QUANTITY = 20

COST_BUFFER_PCT = 0.05